name: CI

on:
    push:
        branches: [main]

jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:
                    - 10
                    - 12
                    - 14
                    - 16
                serverless:
                    - 2.36.0
                    - latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
            - run: npm i
            - run: npm i serverless@${{ matrix.serverless }}
            - run: npm test
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
            - run: npm i
            - run: npm run check-format
            - run: npm run lint
    type:
        name: Type
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
            - run: npm i
            - name: Typescript checks
              run: tsc --noEmit
